# -*- coding: utf-8 -*-
"""Untitled8.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1R3aLDfEHy4B8GrOgf9KtAooLrBUICHLy
"""

#importing pandas as pd
import pandas as pd
# dictionary of lists
dict = {'name':["Sumit","navneet","ritik","anshul"],
        'age':["19",'15','18','20']}
info = pd.DataFrame(dict,index=[True,True,False,True])
print(info)

import numpy as np
arr = np.arange(16)
print("The Original array is: \n", arr)

# shape array with 2 rows and 8 columns
arr = np.arange(16).reshape(2,8)
print("\nreshapedarray:\n",arr)
arr = np.arange(16).reshape(8,2)
print("\nreshaped array:\n",arr)

